### ISSUE TITLE
Cannot run or build code

### ISSUE THREAD

**Issue by Pekarnya** [masterdezign/10-days-of-grad#4]
Hello,

I have followed the installation instructions provided in the README.md and successfully installed the necessary dependencies. However, when I attempt to run the command:
`stack --resolver lts-11.6 --install-ghc runghc --package hmatrix-0.20.2 Iris.hs
`
I encounter the following error:
No setup information found for ghc-8.2.2 on your platform. This probably means a GHC binary distribution has not yet been added for OS key macosx-aarch64.

It appears that GHC version 8.2.2 is not available for my platform (macOS Sonoma 14.7).

Is it possible to change the compiler to a newer version that is compatible with my OS?
I am unable to locate the configuration file where GHC version 8.2.2 is specified. Could you clarify why GHC 8.2.2 is required for this project?
Thank you for your assistance.

Best regards,

**Comment by Pekarnya** [comment]
Anyway, I’ve decided to learn your project, but instead of using Stack, I am using Cabal. Now I can run and experiment with your code.

If you guys have troubles with Stack on macOS M3 processors, just use Cabal.

**Comment by penkovsky** [comment]
Hi @Pekarnya! 

I am glad that the project with Cabal works for you. Indeed, stack was used as an example. Newer versions of Stack should _a priori_ work as well.

I am closing this issue, feel free to reopen if needed.

Have a nice day
